.TH "LLIUREX\-STORE\-CLI" "1" "October 2018" "" ""
.SH "NAME"
\fBlliurex-store-cli\fR
.SH SYNOPSYS
.P
.RS 2
.nf
lliurex\-store\-cli [OPTIONS] package_name [\-\-appimage] [\-\-snap]
.fi
.RE
.SH DESCRIPTION
.P
.RS 2
.nf
Manage packages from the Lliurex Store\.

Mandatory arguments to long options are mandatory for short options too\.

\-s, \-\-search [name]
    Search *name* in the Lliurex Store\. *Name* could be a package name, a descriptive string or anything else related with a program\.

\-v, \-\-view [package]
    Shows extended information for *package*\. *Package* must be a full package name\.

\-i, \-\-install [package]
    Installs package *package*\. *Package* must be a full package name\.

\-r, \-\-remove [package]
    Removes package *package*\. *Package* must be a full package name\.

\-\-appimage
    Enables appimage repository

\-\-snap
    Enables snap store
.fi
.RE
.SH Examples
.P
.RS 2
.nf
* Search for a multimedia player:
`lliurex\-store\-cli \-s player`

* Search for a CAD application in all sources:
`lliurex\-store\-cli \-s CAD \-\-appimage \-\-snap`

* View information for package *firefox\-esr*:
`lliurex\-store\-cli \-v firefox\-esr`

* View information for appimage package *subsurface\.appimage*:
`lliurex\-store\-cli \-v subsurface\.appimage \-\-appimage`

* Install firefox from snap:
`lliurex\-store\-cli \-i firefox\.snap \-\-snap`

* Remove epiphany\-browser:
`lliurex\-store\-cli \-r epiphany\-browser
.fi
.RE
.SH REPORTING BUGS
.P
.RS 2
.nf
Lliurex Github: <https://github\.com/lliurex/lliurex\-store/issues>
.fi
.RE
.P
##SEE ALSO
    Snapcraft: https://snapcraft\.io
    Appimage: https://appimage\.org

